#!/usr/bin/env python3
"""Reference-only baseline stage agent for ExecAgent.

This file is not a runtime executor. It mirrors `workflow.md` and `prompt.md`
so the model can quickly understand the baseline-stage contract.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


STAGE_ID = "baseline"
AGENT_DIR = Path(__file__).resolve().parent
WORKFLOW_PATH = AGENT_DIR / "workflow.md"
PROMPT_PATH = AGENT_DIR / "prompt.md"
TIMESTAMP_WRITER = AGENT_DIR.parent / "utils" / "write_system_timestamp.py"
DURATION_CALCULATOR = AGENT_DIR.parent / "utils" / "calculate_timestamp_diff.py"
TASK_DURATION_BACKFILLER = AGENT_DIR.parent / "utils" / "backfill_task_duration_fields.py"
TASK_METRICS_GENERATOR = AGENT_DIR.parent / "utils" / "generate_JSON" / "generate_task_metrics.py"
STAGE_METRICS_GENERATOR = AGENT_DIR.parent / "utils" / "generate_JSON" / "generate_stage_metrics.py"

READ_RULES = [
    "Read results/{skill_name}/sample/benchmark_manifest.json plus common/ and hard/ sample folders.",
    "For one task, only read that task's task_description.md and workspace/.",
    "Never read skill source files or SKILL.md.",
]

WRITE_RULES = [
    "Write only results/{skill_name}/exec/results/baseline/.",
    "Append stage summary to results/{skill_name}/exec/results/agent_worklog.log.",
    "Do not write with_skill or specs outputs.",
]

STEP_SEQUENCE = [
    "Write results/baseline/stage_start_timestamp.json with write_system_timestamp.py before the first task.",
    "Process functional tasks sequentially in manifest order.",
    "Before reading one task's task_description.md, write results/baseline/tasks/{task_id}/start_timestamp.json.",
    "Generate task_metrics.json skeleton before each task.",
    "Write results/, worklog.log, task_metrics.json, start_timestamp.json, and end_timestamp.json for each task.",
    "Run backfill_task_duration_fields.py so task_metrics.json is rewritten canonically from task-local timestamps.",
    "Generate results/baseline/metrics.json after all tasks finish.",
]

HARD_CONSTRAINTS = [
    "This is one of the two required ExecAgent terminal launches.",
    "After baseline is complete, stop this terminal; do not continue into with_skill inside the same session.",
    "Do not use the Task tool.",
    "Do not start subagents.",
    "Do not read the skill source.",
    "Tasks in this stage must run strictly serially in manifest order.",
    "Do not run multiple tasks in parallel, in the background, or in any interleaved fashion.",
    "Implement each task exactly as required; do not simplify the task or silently drop requirements.",
    "If a task cannot be completed truthfully, fail honestly and preserve the failure evidence instead of faking success.",
    "start_timestamp.json and end_timestamp.json must be generated by write_system_timestamp.py.",
    "end_timestamp.json must be generated by write_system_timestamp.py.",
    "The only valid task-time source is the scripted duration backfill path that uses calculate_timestamp_diff.py on the task-local start/end timestamp pair.",
]


def build_reference(context: dict[str, Any] | None = None) -> dict[str, Any]:
    context = context or {}
    return {
        "agent": "ExecAgentBaseline",
        "stage": STAGE_ID,
        "reference_only": True,
        "skill_name": context.get("skill_name", "{SKILL_NAME}"),
        "source_dir": context.get("source_dir", "{SOURCE_DIR}"),
        "workflow_path": str(WORKFLOW_PATH),
        "prompt_path": str(PROMPT_PATH),
        "scripts": {
            "timestamp_writer": str(TIMESTAMP_WRITER),
            "duration_calculator": str(DURATION_CALCULATOR),
            "task_duration_backfiller": str(TASK_DURATION_BACKFILLER),
            "task_metrics_generator": str(TASK_METRICS_GENERATOR),
            "stage_metrics_generator": str(STAGE_METRICS_GENERATOR),
        },
        "read_rules": READ_RULES,
        "write_rules": WRITE_RULES,
        "step_sequence": STEP_SEQUENCE,
        "hard_constraints": HARD_CONSTRAINTS,
    }


def run(context: dict[str, Any]) -> dict[str, Any]:
    reference = build_reference(context)
    return {
        "status": "reference_only",
        "message": "ExecAgent baseline stage reference loaded.",
        "reference": reference,
    }
