#!/usr/bin/env python3
"""Reference-only with_skill stage agent for ExecAgent."""

from __future__ import annotations

from pathlib import Path
from typing import Any


STAGE_ID = "with_skill"
AGENT_DIR = Path(__file__).resolve().parent
WORKFLOW_PATH = AGENT_DIR / "workflow.md"
PROMPT_PATH = AGENT_DIR / "prompt.md"
TIMESTAMP_WRITER = AGENT_DIR.parent / "utils" / "write_system_timestamp.py"
DURATION_CALCULATOR = AGENT_DIR.parent / "utils" / "calculate_timestamp_diff.py"
TASK_DURATION_BACKFILLER = AGENT_DIR.parent / "utils" / "backfill_task_duration_fields.py"
TASK_METRICS_GENERATOR = AGENT_DIR.parent / "utils" / "generate_JSON" / "generate_task_metrics.py"
STAGE_METRICS_GENERATOR = AGENT_DIR.parent / "utils" / "generate_JSON" / "generate_stage_metrics.py"

READ_RULES = [
    "Read results/{skill_name}/sample/benchmark_manifest.json plus common/ and hard/ sample folders.",
    "For one task, read only that task's task_description.md and workspace/.",
    "Read skill files only after stage_start_timestamp.json exists and only for the current task.",
    "Do not preload the whole skill tree.",
]

WRITE_RULES = [
    "Write only results/{skill_name}/exec/results/with_skill/.",
    "Append stage summary to results/{skill_name}/exec/results/agent_worklog.log.",
    "Do not write baseline or specs outputs.",
]

STEP_SEQUENCE = [
    "Write results/with_skill/stage_start_timestamp.json with write_system_timestamp.py before the first task.",
    "Process functional tasks sequentially in manifest order.",
    "Before reading one task's task_description.md, write results/with_skill/tasks/{task_id}/start_timestamp.json.",
    "Generate task_metrics.json skeleton before each task.",
    "Write results/, worklog.log, task_metrics.json, start_timestamp.json, and end_timestamp.json for each task.",
    "Run backfill_task_duration_fields.py so task_metrics.json is rewritten canonically from task-local timestamps.",
    "Backfill files_read with actual skill files and count them into input_characters.",
    "Generate results/with_skill/metrics.json after all tasks finish.",
]

HARD_CONSTRAINTS = [
    "This is one of the two required ExecAgent terminal launches.",
    "Baseline does not need to be complete before this stage starts.",
    "Do not use the Task tool.",
    "Do not start subagents.",
    "Do not preload the entire skill source tree.",
    "Tasks in this stage must run strictly serially in manifest order.",
    "Do not run multiple tasks in parallel, in the background, or in any interleaved fashion.",
    "Implement each task exactly as required; do not simplify the task or silently drop requirements.",
    "If a task cannot be completed truthfully, fail honestly and preserve the failure evidence instead of faking success.",
    "start_timestamp.json and end_timestamp.json must be generated by write_system_timestamp.py.",
    "end_timestamp.json must be generated by write_system_timestamp.py.",
    "The only valid task-time source is the scripted duration backfill path that uses calculate_timestamp_diff.py on the task-local start/end timestamp pair.",
]


def build_reference(context: dict[str, Any] | None = None) -> dict[str, Any]:
    context = context or {}
    return {
        "agent": "ExecAgentWithSkill",
        "stage": STAGE_ID,
        "reference_only": True,
        "skill_name": context.get("skill_name", "{SKILL_NAME}"),
        "source_dir": context.get("source_dir", "{SOURCE_DIR}"),
        "workflow_path": str(WORKFLOW_PATH),
        "prompt_path": str(PROMPT_PATH),
        "scripts": {
            "timestamp_writer": str(TIMESTAMP_WRITER),
            "duration_calculator": str(DURATION_CALCULATOR),
            "task_duration_backfiller": str(TASK_DURATION_BACKFILLER),
            "task_metrics_generator": str(TASK_METRICS_GENERATOR),
            "stage_metrics_generator": str(STAGE_METRICS_GENERATOR),
        },
        "read_rules": READ_RULES,
        "write_rules": WRITE_RULES,
        "step_sequence": STEP_SEQUENCE,
        "hard_constraints": HARD_CONSTRAINTS,
    }


def run(context: dict[str, Any]) -> dict[str, Any]:
    reference = build_reference(context)
    return {
        "status": "reference_only",
        "message": "ExecAgent with_skill stage reference loaded.",
        "reference": reference,
    }
