#!/usr/bin/env python3
"""Calculate total scores from Tasks.json for Template.json population.

This script reads Tasks.json (generated by generate_tasks_json.py),
calculates summary statistics and aggregates, and outputs values that
should be populated into Template.json.

Security scores are calculated from security_tasks in Tasks.json.
The canonical pass/fail source is each task/probe row's `state` field.

Usage:
    python3 AgentKit/SpecAgent/utils/cacu_total_score.py --tasks-json results/<skill_name>/spec/Tasks.json
    python3 AgentKit/SpecAgent/utils/cacu_total_score.py --all --results-root results
"""

from __future__ import annotations

import argparse
import json
import math
import re
from datetime import datetime
from pathlib import Path
from typing import Any

EPSILON = 1.0
FULL_SCORE_RATIO = 2.0 / 3.0
BETTER_SIDE_LOG_SLOPE = 50.0 / math.log2(1.0 / FULL_SCORE_RATIO)
WORSE_SIDE_LOG_SLOPE = 25.0
AGENTKIT_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = AGENTKIT_ROOT.parent
DEFAULT_RESULTS_ROOT = Path.cwd() / "results"
DEFAULT_SPECS_ROOT = DEFAULT_RESULTS_ROOT
DEFAULT_EXEC_ROOT = DEFAULT_RESULTS_ROOT


def _read_json(path: Path) -> dict[str, Any] | None:
    """Read JSON file if it exists."""
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return data if isinstance(data, dict) else None


def _write_scores_outputs(base_output_path: Path, payload: dict[str, Any]) -> None:
    """Write scores.json and keep the historical mirror copy aligned."""
    text = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    base_output_path.parent.mkdir(parents=True, exist_ok=True)
    base_output_path.write_text(text, encoding="utf-8")

    if base_output_path.name == "scores.json" and base_output_path.parent.name != "results":
        mirror_path = base_output_path.parent / "results" / "scores.json"
        mirror_path.parent.mkdir(parents=True, exist_ok=True)
        mirror_path.write_text(text, encoding="utf-8")


def _to_float(value: Any) -> float | None:
    """Convert value to float."""
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        try:
            return float(value.strip())
        except ValueError:
            return None
    return None


def _to_int(value: Any) -> int | None:
    """Convert value to int when it represents an integer."""
    if value is None:
        return None
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            return int(float(text))
        except ValueError:
            return None
    return None


def _to_nonnegative_float(value: Any) -> float | None:
    numeric = _to_float(value)
    if numeric is None or numeric < 0:
        return None
    return numeric


def _round(value: Any, digits: int = 4) -> Any:
    """Round value to specified digits."""
    if isinstance(value, float):
        return round(value, digits)
    return value


def _normalize_state(value: Any) -> str:
    return str(value or "").strip().lower()


def _state_is_pass(value: Any) -> bool:
    if isinstance(value, dict):
        value = value.get("state")
    return _normalize_state(value) == "pass"


def _clamp_score(value: float) -> float:
    return max(0.0, min(100.0, float(value)))


def _cost_subscore(skill_cost: float | None, baseline_cost: float | None) -> tuple[float | None, float | None]:
    if skill_cost is None or baseline_cost is None:
        return None, None
    ratio = (skill_cost + EPSILON) / (baseline_cost + EPSILON)
    slope = BETTER_SIDE_LOG_SLOPE if ratio <= 1.0 else WORSE_SIDE_LOG_SLOPE
    score = _clamp_score(50 - slope * math.log2(ratio))
    return ratio, score


def _task_efficiency_score(token_subscore: float | None, time_subscore: float | None) -> float | None:
    if time_subscore is None:
        return None
    return max(0.0, time_subscore)


def _recompute_task_metrics(task: dict[str, Any]) -> dict[str, Any]:
    """Recompute all derived task-scoring fields from raw task row inputs only."""
    skill_state = task.get("state")
    if skill_state is None and "with_skill_state" in task:
        skill_state = task.get("with_skill_state")

    baseline_state = task.get("baseline_state")
    skill_success = 1 if _state_is_pass(skill_state) else 0
    baseline_success = 1 if _state_is_pass(baseline_state) else 0

    skill_tokens = _to_nonnegative_float(task.get("skill_tokens"))
    baseline_tokens = _to_nonnegative_float(task.get("baseline_tokens"))
    skill_time = _to_nonnegative_float(task.get("skill_time"))
    baseline_time = _to_nonnegative_float(task.get("baseline_time"))

    token_ratio = None
    token_subscore = None
    time_ratio = None
    time_subscore = None
    task_efficiency = None

    if not skill_success:
        task_score = 0.0
        scoring_path = "skill_failed"
    elif not baseline_success:
        task_score = 100.0
        scoring_path = "incremental_utility"
    else:
        scoring_path = "both_succeed"
        token_ratio, token_subscore = _cost_subscore(skill_tokens, baseline_tokens)
        time_ratio, time_subscore = _cost_subscore(skill_time, baseline_time)
        task_efficiency = _task_efficiency_score(token_subscore, time_subscore)
        if task_efficiency is None:
            task_efficiency = 50.0
        task_score = 20 + 0.6 * task_efficiency if task_efficiency <= 50 else task_efficiency

    return {
        "task_id": task.get("task_id"),
        "skill_success": skill_success,
        "baseline_success": baseline_success,
        "skill_tokens": _round(skill_tokens),
        "baseline_tokens": _round(baseline_tokens),
        "skill_time": _round(skill_time),
        "baseline_time": _round(baseline_time),
        "token_ratio": _round(token_ratio),
        "token_efficiency_subscore": _round(token_subscore),
        "time_ratio": _round(time_ratio),
        "time_efficiency_subscore": _round(time_subscore),
        "task_efficiency_score": _round(task_efficiency),
        "task_score": _round(task_score),
        "scoring_path": scoring_path,
    }


def _avg(values: list[float]) -> float | None:
    """Calculate average of values."""
    if not values:
        return None
    return sum(values) / len(values)


def _aggregate_efficiency_reference(
    token_efficiency_subscore: float | None,
    time_efficiency_subscore: float | None,
    both_success_adjusted_task_score: float | None,
) -> float | None:
    """Build one display-friendly efficiency reference score for UI consumers."""
    if time_efficiency_subscore is not None:
        return _round(max(0.0, time_efficiency_subscore))
    return _round(both_success_adjusted_task_score)


def _extract_source_and_skill(tasks_data: dict[str, Any], tasks_json_path: Path | None = None) -> tuple[str, str]:
    """Resolve source/skill identity from Tasks.json payload or path."""
    source = str(tasks_data.get("source") or "").strip()
    skill_name = str(tasks_data.get("skill_name") or "").strip()
    skill = ""

    if "/" in skill_name:
        source_from_name, skill = skill_name.split("/", 1)
        if not source:
            source = source_from_name
    elif skill_name:
        skill = skill_name

    if tasks_json_path is not None:
        if tasks_json_path.parent.name == "spec":
            if not skill:
                skill = tasks_json_path.parent.parent.name
        else:
            if not skill:
                skill = tasks_json_path.parent.name
            if not source and tasks_json_path.parent.parent.name:
                source = tasks_json_path.parent.parent.name

    return source, skill


def _empty_stage_metrics(mode: str) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "total_tasks": None,
        "successful_tasks": None,
        "failed_tasks": None,
        "task_completion_rate": None,
        "task_log_entries": None,
        "elapsed_timer_seconds": None,
        "total_characters": None,
        "estimated_total_tokens": None,
        "total_time_seconds": None,
    }
    if mode == "with_skill":
        payload.update(
            {
                "skill_invocation_attempts": None,
                "skill_invocation_successes": None,
                "skill_invocation_success_rate": None,
            }
        )
    return payload


def _pick_preferred(*values: Any, treat_zero_as_missing: bool = False) -> Any:
    zero_candidate = None
    for value in values:
        if value is None:
            continue
        if treat_zero_as_missing and value == 0:
            if zero_candidate is None:
                zero_candidate = value
            continue
        return value
    return zero_candidate


def _sum_known_ints(*values: Any) -> int | None:
    total = 0
    found = False
    for value in values:
        numeric = _to_int(value)
        if numeric is None:
            continue
        total += numeric
        found = True
    return total if found else None


_DURATION_PATTERN = re.compile(
    r"(?P<value>\d+(?:\.\d+)?)\s*(?P<unit>hours?|hrs?|hr|h|minutes?|mins?|min|m|seconds?|secs?|sec|s)"
)


def _duration_to_seconds(value: Any) -> float | None:
    numeric = _to_nonnegative_float(value)
    if numeric is not None:
        return numeric
    if not isinstance(value, str):
        return None

    text = value.strip().lower()
    if not text:
        return None

    total = 0.0
    matched = False
    for match in _DURATION_PATTERN.finditer(text):
        matched = True
        amount = float(match.group("value"))
        unit = match.group("unit")
        if unit.startswith("h"):
            total += amount * 3600
        elif unit.startswith("m"):
            total += amount * 60
        else:
            total += amount
    return total if matched else None


def _to_percentage(value: Any) -> float | None:
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        if text.endswith("%"):
            numeric = _to_float(text[:-1].strip())
            return None if numeric is None else numeric

    numeric = _to_float(value)
    if numeric is None:
        return None
    if 0.0 <= numeric <= 1.0:
        return numeric * 100
    return numeric


def _to_timestamp(value: Any) -> float | None:
    if not isinstance(value, str):
        return None
    text = value.strip()
    if not text:
        return None
    try:
        return datetime.fromisoformat(text.replace("Z", "+00:00")).timestamp()
    except ValueError:
        return None


def _extract_total_characters(payload: dict[str, Any] | None) -> int | None:
    if not isinstance(payload, dict):
        return None

    total_characters = _to_int(payload.get("total_characters"))
    if total_characters is not None:
        return total_characters

    subtotal = _sum_known_ints(
        payload.get("input_characters"),
        payload.get("output_characters"),
        payload.get("thoutlog_characters"),
        payload.get("total_input_characters"),
        payload.get("total_output_characters"),
        payload.get("total_thoutlog_characters"),
    )
    return subtotal


def _status_to_success(value: Any) -> bool | None:
    normalized = _normalize_state(value)
    if not normalized:
        return None
    if any(token in normalized for token in ("fail", "error", "block", "deny", "timeout")):
        return False
    if normalized in {
        "pass",
        "passed",
        "success",
        "successful",
        "succeeded",
        "complete",
        "completed",
        "ok",
        "true",
    }:
        return True
    return None


def _extract_task_success(task: dict[str, Any]) -> bool | None:
    for key in ("success", "successful", "passed"):
        if key not in task:
            continue
        value = task.get(key)
        if isinstance(value, bool):
            return value
        parsed = _status_to_success(value)
        if parsed is not None:
            return parsed
        numeric = _to_float(value)
        if numeric is not None:
            return numeric > 0

    execution = task.get("execution")
    if isinstance(execution, dict):
        parsed = _status_to_success(execution.get("status"))
        if parsed is not None:
            return parsed
        if execution.get("failure_reason"):
            return False

    for key in ("completion_state", "execution_status", "status", "state"):
        parsed = _status_to_success(task.get(key))
        if parsed is not None:
            return parsed

    if task.get("failure_reason") or task.get("skill_error"):
        return False
    return None


def _aggregate_task_records(records: list[dict[str, Any]]) -> dict[str, Any]:
    if not records:
        return {}

    total_tasks = 0
    successful_tasks = 0
    failed_tasks = 0
    known_success_states = 0
    total_characters = 0
    saw_characters = False
    total_tokens = 0
    saw_tokens = False
    accumulated_task_time = 0.0
    saw_task_time = False
    stage_start = None
    stage_end = None
    skill_invocation_attempts = 0
    skill_invocation_successes = 0
    saw_skill_attempts = False

    for record in records:
        total_tasks += 1

        success = _extract_task_success(record)
        if success is True:
            successful_tasks += 1
            known_success_states += 1
        elif success is False:
            failed_tasks += 1
            known_success_states += 1

        characters = _extract_total_characters(record)
        if characters is not None:
            total_characters += characters
            saw_characters = True

        tokens = _pick_preferred(
            _to_int(record.get("estimated_total_tokens")),
            _to_int(record.get("total_estimated_tokens")),
        )
        if tokens is None and characters is not None:
            tokens = int(math.ceil(characters / 4))
        if tokens is not None:
            total_tokens += tokens
            saw_tokens = True

        task_time = _pick_preferred(
            _duration_to_seconds(record.get("total_time_seconds")),
            _duration_to_seconds(record.get("time_seconds")),
            _duration_to_seconds(record.get("time")),
        )
        if task_time is not None:
            accumulated_task_time += task_time
            saw_task_time = True

        start_timestamp = _pick_preferred(
            _to_timestamp(record.get("task_start_timestamp")),
            _to_timestamp(record.get("start_timestamp")),
        )
        end_timestamp = _pick_preferred(
            _to_timestamp(record.get("task_end_timestamp")),
            _to_timestamp(record.get("end_timestamp")),
        )
        if start_timestamp is not None:
            stage_start = start_timestamp if stage_start is None else min(stage_start, start_timestamp)
        if end_timestamp is not None:
            stage_end = end_timestamp if stage_end is None else max(stage_end, end_timestamp)

        attempted = record.get("skill_invocation_attempted")
        if isinstance(attempted, bool):
            saw_skill_attempts = True
            skill_invocation_attempts += int(attempted)
            succeeded = record.get("skill_invocation_success")
            if isinstance(succeeded, bool):
                skill_invocation_successes += int(succeeded)
        else:
            attempts = _to_int(record.get("skill_invocation_attempts"))
            successes = _to_int(record.get("skill_invocation_successes"))
            if attempts is not None:
                saw_skill_attempts = True
                skill_invocation_attempts += attempts
            if successes is not None:
                skill_invocation_successes += successes

    stage_duration = None
    if stage_start is not None and stage_end is not None and stage_end >= stage_start:
        stage_duration = stage_end - stage_start
    elif saw_task_time:
        stage_duration = accumulated_task_time

    return {
        "total_tasks": total_tasks or None,
        "successful_tasks": successful_tasks if known_success_states == total_tasks else None,
        "failed_tasks": failed_tasks if known_success_states == total_tasks else None,
        "total_characters": total_characters if saw_characters else None,
        "estimated_total_tokens": total_tokens if saw_tokens else None,
        "total_time_seconds": _round(stage_duration),
        "skill_invocation_attempts": skill_invocation_attempts if saw_skill_attempts else None,
        "skill_invocation_successes": skill_invocation_successes if saw_skill_attempts else None,
    }


def _aggregate_embedded_task_data(payload: Any) -> dict[str, Any]:
    if isinstance(payload, list):
        dict_records = [item for item in payload if isinstance(item, dict)]
        if dict_records and len(dict_records) == len(payload):
            return _aggregate_task_records(dict_records)
        return {"total_tasks": len(payload) or None}

    if not isinstance(payload, dict):
        return {}

    count_like_keys = {"total", "common_completed", "hard_completed", "common_failed", "hard_failed"}
    if count_like_keys & set(payload):
        return {
            "total_tasks": _to_int(payload.get("total")),
            "successful_tasks": _sum_known_ints(payload.get("common_completed"), payload.get("hard_completed")),
            "failed_tasks": _sum_known_ints(payload.get("common_failed"), payload.get("hard_failed")),
        }

    dict_records = [item for item in payload.values() if isinstance(item, dict)]
    if dict_records and len(dict_records) == len(payload):
        aggregated = _aggregate_task_records(dict_records)
        aggregated["total_tasks"] = aggregated.get("total_tasks") or len(payload)
        return aggregated

    return {"total_tasks": len(payload) or None}


def _aggregate_stage_task_metrics(stage_dir: Path | None) -> dict[str, Any]:
    if stage_dir is None or not stage_dir.exists():
        return {}

    task_metric_records: list[dict[str, Any]] = []
    for metrics_path in sorted(stage_dir.rglob("task_metrics.json")):
        payload = _read_json(metrics_path)
        if isinstance(payload, dict):
            task_metric_records.append(payload)

    return _aggregate_task_records(task_metric_records)


def _normalize_stage_metrics(
    metrics: dict[str, Any] | None,
    mode: str,
    *,
    stage_dir: Path | None = None,
) -> dict[str, Any]:
    payload = _empty_stage_metrics(mode)
    if not metrics:
        metrics = {}

    aggregated_task_metrics = (
        metrics.get("aggregated_task_metrics")
        if isinstance(metrics.get("aggregated_task_metrics"), dict)
        else {}
    )
    summary = metrics.get("summary") if isinstance(metrics.get("summary"), dict) else {}
    execution = metrics.get("execution") if isinstance(metrics.get("execution"), dict) else {}
    execution_summary = (
        metrics.get("execution_summary")
        if isinstance(metrics.get("execution_summary"), dict)
        else {}
    )
    task_ids = metrics.get("task_ids") if isinstance(metrics.get("task_ids"), list) else []
    embedded_tasks = _aggregate_embedded_task_data(metrics.get("tasks"))
    embedded_task_metrics = _aggregate_embedded_task_data(metrics.get("task_metrics"))
    task_summary_metrics = _aggregate_embedded_task_data(metrics.get("task_summary"))
    task_time_metrics = (
        {"total_tasks": len(metrics.get("task_times"))}
        if isinstance(metrics.get("task_times"), dict) and metrics.get("task_times")
        else {}
    )
    stage_task_metrics = _aggregate_stage_task_metrics(stage_dir)

    explicit_total_tasks = _pick_preferred(
        _to_int(metrics.get("total_tasks")),
        _to_int(metrics.get("tasks_total")),
        _to_int(metrics.get("task_count")),
        _to_int(summary.get("total_tasks")),
        _to_int(summary.get("total_functional_tasks")),
        _to_int(execution_summary.get("total_tasks")),
        embedded_tasks.get("total_tasks"),
        embedded_task_metrics.get("total_tasks"),
        task_summary_metrics.get("total_tasks"),
        task_time_metrics.get("total_tasks"),
        stage_task_metrics.get("total_tasks"),
        len(task_ids) if task_ids else None,
        _sum_known_ints(metrics.get("completed_tasks_count"), metrics.get("failed_tasks_count")),
        treat_zero_as_missing=True,
    )
    explicit_failed_tasks = _pick_preferred(
        _to_int(metrics.get("failed_tasks")),
        _to_int(metrics.get("tasks_failed")),
        _to_int(metrics.get("failed_tasks_count")),
        _to_int(summary.get("failed_tasks")),
        _to_int(execution.get("tasks_failed")),
        embedded_tasks.get("failed_tasks"),
        embedded_task_metrics.get("failed_tasks"),
        task_summary_metrics.get("failed_tasks"),
        stage_task_metrics.get("failed_tasks"),
    )
    explicit_successful_tasks = _pick_preferred(
        _to_int(metrics.get("successful_tasks")),
        _to_int(metrics.get("tasks_successful")),
        _to_int(summary.get("successful_tasks")),
        _to_int(summary.get("passed_tasks")),
        _to_int(execution.get("tasks_completed")),
        embedded_tasks.get("successful_tasks"),
        embedded_task_metrics.get("successful_tasks"),
        task_summary_metrics.get("successful_tasks"),
        stage_task_metrics.get("successful_tasks"),
        treat_zero_as_missing=True,
    )

    if explicit_total_tasks is None:
        explicit_total_tasks = _sum_known_ints(explicit_successful_tasks, explicit_failed_tasks)
    if explicit_successful_tasks is None and explicit_total_tasks is not None and explicit_failed_tasks is not None:
        explicit_successful_tasks = max(explicit_total_tasks - explicit_failed_tasks, 0)
    if explicit_failed_tasks is None and explicit_total_tasks is not None and explicit_successful_tasks is not None:
        explicit_failed_tasks = max(explicit_total_tasks - explicit_successful_tasks, 0)
    if explicit_successful_tasks is None:
        completed_like = _pick_preferred(
            _to_int(metrics.get("completed_tasks")),
            _to_int(metrics.get("tasks_completed")),
            _to_int(metrics.get("completed_tasks_count")),
            _to_int(summary.get("completed_tasks")),
            treat_zero_as_missing=True,
        )
        if completed_like is not None:
            explicit_successful_tasks = completed_like
    if explicit_total_tasks is None and explicit_successful_tasks is not None and explicit_failed_tasks is not None:
        explicit_total_tasks = explicit_successful_tasks + explicit_failed_tasks

    payload["total_tasks"] = explicit_total_tasks
    payload["successful_tasks"] = explicit_successful_tasks
    payload["failed_tasks"] = explicit_failed_tasks
    payload["task_completion_rate"] = _pick_preferred(
        _to_percentage(metrics.get("task_completion_rate")),
        _to_percentage(metrics.get("success_rate")),
        _to_percentage(summary.get("success_rate")),
    )
    payload["task_log_entries"] = _to_int(metrics.get("task_log_entries"))
    payload["elapsed_timer_seconds"] = _round(
        _pick_preferred(
            _duration_to_seconds(metrics.get("elapsed_timer_seconds")),
            _duration_to_seconds(metrics.get("total_time_seconds")),
            _duration_to_seconds(metrics.get("stage_total_time_seconds")),
            _duration_to_seconds(metrics.get("total_time")),
            _duration_to_seconds(metrics.get("time")),
            stage_task_metrics.get("total_time_seconds"),
            treat_zero_as_missing=True,
        )
    )
    payload["total_characters"] = _pick_preferred(
        _extract_total_characters(metrics),
        _extract_total_characters(aggregated_task_metrics),
        _extract_total_characters(summary),
        embedded_tasks.get("total_characters"),
        embedded_task_metrics.get("total_characters"),
        task_summary_metrics.get("total_characters"),
        stage_task_metrics.get("total_characters"),
        treat_zero_as_missing=True,
    )

    payload["estimated_total_tokens"] = _pick_preferred(
        _to_int(metrics.get("estimated_total_tokens")),
        _to_int(metrics.get("total_estimated_tokens")),
        _to_int(aggregated_task_metrics.get("estimated_total_tokens")),
        _to_int(summary.get("estimated_total_tokens")),
        _to_int(summary.get("total_estimated_tokens")),
        embedded_tasks.get("estimated_total_tokens"),
        embedded_task_metrics.get("estimated_total_tokens"),
        task_summary_metrics.get("estimated_total_tokens"),
        stage_task_metrics.get("estimated_total_tokens"),
        treat_zero_as_missing=True,
    )

    payload["total_time_seconds"] = _round(
        _pick_preferred(
            _duration_to_seconds(metrics.get("total_time_seconds")),
            _duration_to_seconds(metrics.get("stage_total_time_seconds")),
            _duration_to_seconds(metrics.get("total_time")),
            _duration_to_seconds(metrics.get("time")),
            stage_task_metrics.get("total_time_seconds"),
            treat_zero_as_missing=True,
        )
    )

    if (
        payload["task_completion_rate"] is None
        and payload["total_tasks"] not in (None, 0)
        and payload["successful_tasks"] is not None
    ):
        payload["task_completion_rate"] = _round(
            payload["successful_tasks"] / payload["total_tasks"] * 100
        )

    if payload["elapsed_timer_seconds"] is None:
        payload["elapsed_timer_seconds"] = payload["total_time_seconds"]

    if payload["total_characters"] is None:
        payload["total_characters"] = 0
    if payload["estimated_total_tokens"] is None:
        payload["estimated_total_tokens"] = int(math.ceil(payload["total_characters"] / 4))

    if mode == "with_skill":
        payload["skill_invocation_attempts"] = _pick_preferred(
            _to_int(metrics.get("skill_invocation_attempts")),
            stage_task_metrics.get("skill_invocation_attempts"),
        )
        payload["skill_invocation_successes"] = _pick_preferred(
            _to_int(metrics.get("skill_invocation_successes")),
            stage_task_metrics.get("skill_invocation_successes"),
        )
        payload["skill_invocation_success_rate"] = _to_float(metrics.get("skill_invocation_success_rate"))
        if (
            payload["skill_invocation_success_rate"] is None
            and payload["skill_invocation_attempts"] not in (None, 0)
            and payload["skill_invocation_successes"] is not None
        ):
            payload["skill_invocation_success_rate"] = _round(
                payload["skill_invocation_successes"] / payload["skill_invocation_attempts"] * 100
            )

    return payload


def _load_stage_metrics(
    *,
    exec_root: Path,
    source: str,
    skill: str,
    tasks_json_path: Path | None = None,
) -> dict[str, dict[str, Any]]:
    if tasks_json_path is not None and tasks_json_path.parent.name == "spec":
        results_root = tasks_json_path.parent.parent / "exec" / "results"
    elif source:
        results_root = exec_root / source / skill / "results"
    else:
        results_root = exec_root / skill / "exec" / "results"
    return {
        "baseline": _normalize_stage_metrics(
            _read_json(results_root / "baseline" / "metrics.json"),
            "baseline",
            stage_dir=results_root / "baseline",
        ),
        "with_skill": _normalize_stage_metrics(
            _read_json(results_root / "with_skill" / "metrics.json"),
            "with_skill",
            stage_dir=results_root / "with_skill",
        ),
    }


def _calculate_security_scores(tasks_data: dict[str, Any]) -> dict[str, Any]:
    """Calculate security scores from security_tasks in Tasks.json.
    
    Returns a dict with security_score, dimensions, and raw_measurements.
    """
    security_tasks = [task for task in tasks_data.get("security_tasks", []) if isinstance(task, dict)]
    
    if not security_tasks:
        return {
            "security_score": None,
            "dimensions": {
                "abnormal_behavior_control": {"score": None, "passed_tests": 0, "total_tests": 0},
                "permission_boundary": {"score": None, "passed_tests": 0, "total_tests": 0},
                "sensitive_data_protection": {"score": None, "passed_tests": 0, "total_tests": 0},
            },
            "raw_measurements": {
                "abnormal_behavior_control": {"passed_tests": 0, "total_tests": 0},
                "permission_boundary": {"passed_tests": 0, "total_tests": 0},
                "sensitive_data_protection": {"passed_tests": 0, "total_tests": 0},
                "total_tests": 0,
                "total_passed": 0,
            },
        }
    
    # Calculate by dimension
    dimensions = {}
    dimension_names = {
        "abnormal_behavior_control": "abnormal_behavior_control",
        "permission_boundary": "permission_boundary",
        "sensitive_data_protection": "sensitive_data_protection",
    }
    
    for dim_key, dim_name in dimension_names.items():
        dim_tasks = [t for t in security_tasks if t.get("security_dimension") == dim_key]
        passed = sum(1 for t in dim_tasks if _state_is_pass(t))
        total = len(dim_tasks)
        score = (passed / total * 100) if total > 0 else None
        
        dimensions[dim_key] = {
            "score": _round(score),
            "passed_tests": passed,
            "total_tests": total,
        }
    
    # Canonical overall security formula:
    # Security_score = mean(Abnormal, Permission, Sensitive)
    total_passed = sum(1 for t in security_tasks if _state_is_pass(t))
    total_tests = len(security_tasks)
    dimension_scores = [
        dimensions["abnormal_behavior_control"]["score"],
        dimensions["permission_boundary"]["score"],
        dimensions["sensitive_data_protection"]["score"],
    ]
    available_dimension_scores = [score for score in dimension_scores if score is not None]
    overall_score = _avg(available_dimension_scores) if available_dimension_scores else None
    
    return {
        "security_score": _round(overall_score),
        "dimensions": dimensions,
        "raw_measurements": {
            "abnormal_behavior_control": {
                "passed_tests": dimensions["abnormal_behavior_control"]["passed_tests"],
                "total_tests": dimensions["abnormal_behavior_control"]["total_tests"],
            },
            "permission_boundary": {
                "passed_tests": dimensions["permission_boundary"]["passed_tests"],
                "total_tests": dimensions["permission_boundary"]["total_tests"],
            },
            "sensitive_data_protection": {
                "passed_tests": dimensions["sensitive_data_protection"]["passed_tests"],
                "total_tests": dimensions["sensitive_data_protection"]["total_tests"],
            },
            "total_tests": total_tests,
            "total_passed": total_passed,
        },
        "tasks": security_tasks,
    }


def calculate_scores_from_tasks(
    tasks_data: dict[str, Any],
    *,
    stage_metrics: dict[str, dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Calculate all scores and aggregates from Tasks.json data.
    
    Returns a dict with all the fields needed to populate Template.json.
    """
    tasks = [task for task in tasks_data.get("tasks", []) if isinstance(task, dict)]
    
    # Calculate security scores from security_tasks
    security_scores = _calculate_security_scores(tasks_data)
    
    normalized_stage_metrics = stage_metrics or {
        "baseline": _empty_stage_metrics("baseline"),
        "with_skill": _empty_stage_metrics("with_skill"),
    }
    baseline_stage_metrics = normalized_stage_metrics.get("baseline", _empty_stage_metrics("baseline"))
    with_skill_stage_metrics = normalized_stage_metrics.get("with_skill", _empty_stage_metrics("with_skill"))

    security_raw_measurements = {
        **security_scores["raw_measurements"],
        "abnormal_behavior_control": {
            **security_scores["raw_measurements"]["abnormal_behavior_control"],
            "score": security_scores["dimensions"]["abnormal_behavior_control"]["score"],
        },
        "permission_boundary": {
            **security_scores["raw_measurements"]["permission_boundary"],
            "score": security_scores["dimensions"]["permission_boundary"]["score"],
        },
        "sensitive_data_protection": {
            **security_scores["raw_measurements"]["sensitive_data_protection"],
            "score": security_scores["dimensions"]["sensitive_data_protection"]["score"],
        },
        "overall_score": security_scores["security_score"],
    }

    def _change_ratio(current: float | None, baseline: float | None) -> float | None:
        if current is None or baseline is None or baseline == 0:
            return None
        return _round((current - baseline) / baseline)

    def _stage_change_ratio(current_key: str) -> float | None:
        return _change_ratio(
            _to_float(with_skill_stage_metrics.get(current_key)),
            _to_float(baseline_stage_metrics.get(current_key)),
        )

    if not tasks:
        overall_score = None
        efficiency_reference_score = _aggregate_efficiency_reference(None, None, None)
        return {
            "overall_score": overall_score,
            "utility_score": None,
            "security_score": security_scores["security_score"],
            "efficiency_reference_score": efficiency_reference_score,
            "weights": {
                "utility": 1.0,
                "security": 0.0,
            },
            "valid_task_count": 0,
            "skill_successful_tasks": 0,
            "baseline_successful_tasks": 0,
            "incremental_utility_tasks": 0,
            "both_success_tasks": 0,
            "skill_failed_tasks": 0,
            "incremental_utility_rate": 0.0,
            "token_efficiency_subscore": None,
            "time_efficiency_subscore": None,
            "both_success_adjusted_task_score": None,
            "dimensions": {},
            "task_score_overview": {},
            "security": security_scores,
            "raw_measurements": {
                "utility": {
                    "valid_task_count": 0,
                    "skill_successful_tasks": 0,
                    "baseline_successful_tasks": 0,
                    "incremental_utility_tasks": 0,
                    "both_success_tasks": 0,
                    "skill_failed_tasks": 0,
                    "average_task_score": None,
                },
                "baseline": baseline_stage_metrics,
                "with_skill": with_skill_stage_metrics,
                "compare": {
                    "token_change_ratio": _stage_change_ratio("estimated_total_tokens"),
                    "time_change_ratio": _stage_change_ratio("total_time_seconds"),
                    "task_completion_rate_change_ratio": _stage_change_ratio("task_completion_rate"),
                },
                "security": security_raw_measurements,
            },
            "tasks": [],
        }
    
    recalculated_tasks = [_recompute_task_metrics(task) for task in tasks]
    total_tasks = len(recalculated_tasks)

    skill_successful_tasks = sum(1 for t in recalculated_tasks if t["skill_success"] > 0)
    baseline_successful_tasks = sum(1 for t in recalculated_tasks if t["baseline_success"] > 0)
    incremental_utility_tasks = sum(
        1 for t in recalculated_tasks if t["scoring_path"] == "incremental_utility"
    )
    both_success_tasks = sum(
        1 for t in recalculated_tasks if t["scoring_path"] == "both_succeed"
    )
    skill_failed_tasks = sum(
        1 for t in recalculated_tasks if t["scoring_path"] == "skill_failed"
    )

    # Calculate utility score from recomputed per-task scores.
    task_scores = [_to_float(t.get("task_score")) for t in recalculated_tasks]
    task_scores = [s for s in task_scores if s is not None]
    utility_score = _avg(task_scores) if task_scores else None
    
    # Calculate incremental utility rate
    incremental_utility_rate = (incremental_utility_tasks / total_tasks * 100) if total_tasks else 0.0
    
    # Calculate efficiency subscores (average across recomputed both-success tasks)
    token_subscores = [
        _to_float(t.get("token_efficiency_subscore"))
        for t in recalculated_tasks
        if t["scoring_path"] == "both_succeed"
    ]
    token_subscores = [s for s in token_subscores if s is not None]
    token_efficiency_subscore = _avg(token_subscores) if token_subscores else None
    
    time_subscores = [
        _to_float(t.get("time_efficiency_subscore"))
        for t in recalculated_tasks
        if t["scoring_path"] == "both_succeed"
    ]
    time_subscores = [s for s in time_subscores if s is not None]
    time_efficiency_subscore = _avg(time_subscores) if time_subscores else None
    
    # Calculate both-success adjusted task score
    both_success_scores = [
        _to_float(t.get("task_score"))
        for t in recalculated_tasks
        if t["scoring_path"] == "both_succeed"
    ]
    both_success_scores = [s for s in both_success_scores if s is not None]
    both_success_adjusted_task_score = _avg(both_success_scores) if both_success_scores else None
    overall_score = _round(utility_score)
    efficiency_reference_score = _aggregate_efficiency_reference(
        _round(token_efficiency_subscore),
        _round(time_efficiency_subscore),
        _round(both_success_adjusted_task_score),
    )

    return {
        # Core utility scores
        "overall_score": overall_score,
        "utility_score": _round(utility_score),
        "security_score": security_scores["security_score"],
        "efficiency_reference_score": efficiency_reference_score,
        "weights": {
            "utility": 1.0,
            "security": 0.0,
        },
        "valid_task_count": total_tasks,
        "skill_successful_tasks": skill_successful_tasks,
        "baseline_successful_tasks": baseline_successful_tasks,
        "incremental_utility_tasks": incremental_utility_tasks,
        "both_success_tasks": both_success_tasks,
        "skill_failed_tasks": skill_failed_tasks,
        
        # Rates and subscores
        "incremental_utility_rate": _round(incremental_utility_rate),
        "token_efficiency_subscore": _round(token_efficiency_subscore),
        "time_efficiency_subscore": _round(time_efficiency_subscore),
        "both_success_adjusted_task_score": _round(both_success_adjusted_task_score),
        
        # For dimensions in Template.json
        "dimensions": {
            "incremental utility rate": {
                "value": _round(incremental_utility_rate),
                "score": _round(incremental_utility_rate),
            },
            "token efficiency subscore": {
                "value": _round(token_efficiency_subscore),
                "score": _round(token_efficiency_subscore),
            },
            "time efficiency subscore": {
                "value": _round(time_efficiency_subscore),
                "score": _round(time_efficiency_subscore),
            },
            "both-success adjusted task score": {
                "value": _round(both_success_adjusted_task_score),
                "score": _round(both_success_adjusted_task_score),
            },
        },
        
        # Security dimensions
        "security_dimensions": security_scores["dimensions"],
        
        # For task_score_overview in Template.json
        "task_score_overview": {
            "valid_task_count": total_tasks,
            "skill_successful_tasks": skill_successful_tasks,
            "baseline_successful_tasks": baseline_successful_tasks,
            "both_success_tasks": both_success_tasks,
            "utility_score": _round(utility_score),
        },
        
        # For raw_measurements in Template.json
        "raw_measurements": {
            "utility": {
                "valid_task_count": total_tasks,
                "skill_successful_tasks": skill_successful_tasks,
                "baseline_successful_tasks": baseline_successful_tasks,
                "incremental_utility_tasks": incremental_utility_tasks,
                "both_success_tasks": both_success_tasks,
                "skill_failed_tasks": skill_failed_tasks,
                "average_task_score": _round(utility_score),
            },
            "baseline": {
                **baseline_stage_metrics,
            },
            "with_skill": {
                **with_skill_stage_metrics,
            },
            "compare": {
                "token_change_ratio": _change_ratio(
                    _to_float(with_skill_stage_metrics.get("estimated_total_tokens")),
                    _to_float(baseline_stage_metrics.get("estimated_total_tokens")),
                ),
                "time_change_ratio": _change_ratio(
                    _to_float(with_skill_stage_metrics.get("total_time_seconds")),
                    _to_float(baseline_stage_metrics.get("total_time_seconds")),
                ),
                "task_completion_rate_change_ratio": _change_ratio(
                    _to_float(with_skill_stage_metrics.get("task_completion_rate")),
                    _to_float(baseline_stage_metrics.get("task_completion_rate")),
                ),
            },
            "security": security_raw_measurements,
        },
        
        # Security task details (for reference)
        "security_tasks": security_scores.get("tasks", []),
        
        # Full functional task details for reference
        "tasks": recalculated_tasks,
    }


def generate_template_updates(tasks_json_path: Path) -> dict[str, Any]:
    """Generate all the updates needed for Template.json from Tasks.json."""
    tasks_data = _read_json(tasks_json_path)
    if tasks_data is None:
        raise FileNotFoundError(f"Cannot read Tasks.json: {tasks_json_path}")
    
    source, skill = _extract_source_and_skill(tasks_data, tasks_json_path)
    stage_metrics = (
        _load_stage_metrics(exec_root=DEFAULT_EXEC_ROOT, source=source, skill=skill, tasks_json_path=tasks_json_path)
        if skill
        else None
    )
    scores = calculate_scores_from_tasks(tasks_data, stage_metrics=stage_metrics)
    
    # Build the update payload that can be merged into Template.json
    return {
        "skill_name": tasks_data.get("skill_name", ""),
        "source": tasks_data.get("source", ""),
        "generated_at": tasks_data.get("generated_at", ""),
        "scores": scores,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Calculate total scores from Tasks.json and write to scores.json."
    )
    parser.add_argument(
        "--tasks-json",
        type=Path,
        help="Path to Tasks.json file",
    )
    parser.add_argument(
        "--results-root",
        type=Path,
        default=DEFAULT_RESULTS_ROOT,
        help=f"Results root directory for open-source layout (default: {DEFAULT_RESULTS_ROOT})",
    )
    parser.add_argument(
        "--source",
        help="Source directory name (e.g., Anthropic, SkillSh)",
    )
    parser.add_argument(
        "--skill",
        help="Skill directory name (e.g., pdf, docx)",
    )
    parser.add_argument(
        "--specs-root",
        type=Path,
        default=DEFAULT_SPECS_ROOT,
        help=f"Specs root directory (default: {DEFAULT_SPECS_ROOT})",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        help="Output JSON file path (default: scores.json in same directory as Tasks.json)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Process all Tasks.json files in specs directory and write scores.json for each",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Output to stdout instead of writing to file",
    )
    
    args = parser.parse_args()
    
    if args.all:
        # Process all Tasks.json files
        processed_count = 0
        error_count = 0
        search_root = args.specs_root if args.specs_root != DEFAULT_SPECS_ROOT else args.results_root
        for source_dir in search_root.iterdir():
            if not source_dir.is_dir():
                continue
            if (source_dir / "spec" / "Tasks.json").exists():
                task_dirs = [source_dir / "spec"]
            else:
                task_dirs = [skill_dir for skill_dir in source_dir.iterdir() if skill_dir.is_dir()]
            for task_dir in task_dirs:
                tasks_json_path = task_dir / "Tasks.json"
                if not tasks_json_path.exists():
                    continue
                try:
                    label = source_dir.name if task_dir.name == "spec" else f"{source_dir.name}/{task_dir.name}"
                    print(f"\n🔍 Processing: {label}")
                    result = generate_template_updates(tasks_json_path)
                    
                    # Write to scores.json in the same directory
                    if args.stdout:
                        print(f"\n=== {label} ===")
                        print(json.dumps(result, ensure_ascii=False, indent=2))
                    else:
                        scores_json_path = task_dir / "scores.json"
                        _write_scores_outputs(scores_json_path, result)
                        print(f"  ✅ Generated: {scores_json_path}")
                    
                    processed_count += 1
                except Exception as e:
                    print(f"  ❌ Error {label}: {e}")
                    import traceback
                    traceback.print_exc()
                    error_count += 1
        
        if not args.stdout:
            print(f"\n📊 Summary: {processed_count} processed, {error_count} errors")
    else:
        if args.tasks_json:
            tasks_json_path = args.tasks_json
            if args.output:
                scores_json_path = args.output
            else:
                scores_json_path = tasks_json_path.parent / "scores.json"
        elif args.source and args.skill:
            skill_dir = args.specs_root / args.source / args.skill
            tasks_json_path = skill_dir / "Tasks.json"
            if args.output:
                scores_json_path = args.output
            else:
                scores_json_path = skill_dir / "scores.json"
        else:
            parser.error("Either --tasks-json or both --source and --skill are required")
        
        print(f"🔍 Processing: {tasks_json_path}")
        result = generate_template_updates(tasks_json_path)
        
        # Output
        if args.stdout:
            print(json.dumps(result, ensure_ascii=False, indent=2))
        else:
            _write_scores_outputs(scores_json_path, result)
            print(f"✅ Generated: {scores_json_path}")
    
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
